import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Gift from '../components/Gift'
import Door from '../components/Door'
import DoorModel from '../model/porta'


export default function Home() {
  const p1 = new DoorModel(1)
  const p2 = new DoorModel(2)
  const p3 = new DoorModel(3)
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
     {/* <Gift/> */}
     <div style={{display:"flex"}}>
       <Door door={p1}/>
       <Door door={p2}/>
       <Door door={p3}/>
     </div>
    </>
  )
}