import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Gift from '../components/Gift'
import Door from '../components/Door'
import DoorModel from '../model/door'
import { useState } from 'react'


export default function Home() {
  const [p1,setP1] = useState(new DoorModel(1))
  const [text,setText] = useState("...")

  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
     {/* <Gift/> */}
     <div style={{display:"flex", flexDirection:"column"}}>
      <input type="text" style={{color:"red"}} value={text} onChange={e =>setText(e.target.value)}/>
       <Door value={p1} onChange={newDoor => setP1(newDoor)} />
     </div>
    </>
  )
}